SUB_PROJECTS=
ADD_DL=
ADD_INCLUDE=
ARCH=linux

ifeq ($(BASE_DIR),)
BASE_DIR=$(shell find ~/ -name "rd_syllabus" 2> /dev/null)/project/
endif

################################################################################

include $(BASE_DIR)misc/makefile
